INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_MY_CONSTELLATION_DECODER my_constellation_decoder)

FIND_PATH(
    MY_CONSTELLATION_DECODER_INCLUDE_DIRS
    NAMES my_constellation_decoder/api.h
    HINTS $ENV{MY_CONSTELLATION_DECODER_DIR}/include
        ${PC_MY_CONSTELLATION_DECODER_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    MY_CONSTELLATION_DECODER_LIBRARIES
    NAMES gnuradio-my_constellation_decoder
    HINTS $ENV{MY_CONSTELLATION_DECODER_DIR}/lib
        ${PC_MY_CONSTELLATION_DECODER_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(MY_CONSTELLATION_DECODER DEFAULT_MSG MY_CONSTELLATION_DECODER_LIBRARIES MY_CONSTELLATION_DECODER_INCLUDE_DIRS)
MARK_AS_ADVANCED(MY_CONSTELLATION_DECODER_LIBRARIES MY_CONSTELLATION_DECODER_INCLUDE_DIRS)

