INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_MY_CARRIER_ALLOCATOR my_carrier_allocator)

FIND_PATH(
    MY_CARRIER_ALLOCATOR_INCLUDE_DIRS
    NAMES my_carrier_allocator/api.h
    HINTS $ENV{MY_CARRIER_ALLOCATOR_DIR}/include
        ${PC_MY_CARRIER_ALLOCATOR_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    MY_CARRIER_ALLOCATOR_LIBRARIES
    NAMES gnuradio-my_carrier_allocator
    HINTS $ENV{MY_CARRIER_ALLOCATOR_DIR}/lib
        ${PC_MY_CARRIER_ALLOCATOR_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(MY_CARRIER_ALLOCATOR DEFAULT_MSG MY_CARRIER_ALLOCATOR_LIBRARIES MY_CARRIER_ALLOCATOR_INCLUDE_DIRS)
MARK_AS_ADVANCED(MY_CARRIER_ALLOCATOR_LIBRARIES MY_CARRIER_ALLOCATOR_INCLUDE_DIRS)

